export const featuredCourses = [
  {
    id: "1",
    title: "Complete Web Development Bootcamp",
    description: "Master modern web development with HTML, CSS, JavaScript, React, Node.js, and more.",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=600&fit=crop",
    instructor: "Sarah Johnson",
    duration: "40 hours",
    students: 12543,
    rating: 4.8,
    price: 79.99,
    category: "Web Development",
  },
  {
    id: "2",
    title: "Machine Learning A-Z™: AI, Python & R",
    description: "Learn to create Machine Learning Algorithms in Python and R from top Data Science experts.",
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=600&fit=crop",
    instructor: "Dr. Michael Chen",
    duration: "44 hours",
    students: 8921,
    rating: 4.9,
    price: 89.99,
    category: "Data Science",
  },
  {
    id: "3",
    title: "UI/UX Design Masterclass",
    description: "Learn user interface & user experience design from beginner to advanced level.",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=600&fit=crop",
    instructor: "Emily Rodriguez",
    duration: "30 hours",
    students: 15632,
    rating: 4.7,
    price: 69.99,
    category: "Design",
  },
  {
    id: "4",
    title: "Digital Marketing Mastery 2024",
    description: "Complete guide to SEO, social media, email marketing, and online advertising.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop",
    instructor: "David Kim",
    duration: "25 hours",
    students: 9876,
    rating: 4.6,
    price: 59.99,
    category: "Marketing",
  },
  {
    id: "5",
    title: "iOS App Development with Swift",
    description: "Build professional iOS applications from scratch using Swift and SwiftUI.",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
    instructor: "Jennifer Park",
    duration: "35 hours",
    students: 6543,
    rating: 4.8,
    price: 84.99,
    category: "Mobile Development",
  },
  {
    id: "6",
    title: "Cloud Computing with AWS",
    description: "Master Amazon Web Services and become a certified cloud architect.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop",
    instructor: "Robert Martinez",
    duration: "38 hours",
    students: 11234,
    rating: 4.9,
    price: 94.99,
    category: "Cloud Computing",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Alex Thompson",
    role: "Full Stack Developer",
    avatar: "https://i.pravatar.cc/150?img=1",
    content: "EduFlow transformed my career. The courses are well-structured, and the instructors are top-notch. I landed my dream job within 3 months!",
    rating: 5,
  },
  {
    id: 2,
    name: "Maria Garcia",
    role: "UX Designer",
    avatar: "https://i.pravatar.cc/150?img=5",
    content: "The design courses here are exceptional. I've learned more practical skills in a few weeks than I did in years of traditional education.",
    rating: 5,
  },
  {
    id: 3,
    name: "James Wilson",
    role: "Data Scientist",
    avatar: "https://i.pravatar.cc/150?img=7",
    content: "Outstanding platform with real-world projects. The machine learning course helped me transition from finance to tech seamlessly.",
    rating: 5,
  },
  {
    id: 4,
    name: "Sophia Lee",
    role: "Marketing Manager",
    avatar: "https://i.pravatar.cc/150?img=9",
    content: "The digital marketing course exceeded my expectations. Practical, up-to-date, and results-driven. Highly recommended!",
    rating: 5,
  },
];

export const pricingPlans = [
  {
    id: 1,
    name: "Free",
    price: 0,
    period: "forever",
    description: "Perfect for trying out our platform",
    features: [
      "Access to 5 free courses",
      "Basic course materials",
      "Community forum access",
      "Mobile app access",
    ],
    cta: "Get Started",
    highlighted: false,
  },
  {
    id: 2,
    name: "Pro",
    price: 29,
    period: "month",
    description: "Best for serious learners",
    features: [
      "Unlimited course access",
      "Downloadable resources",
      "Priority support",
      "Certificates of completion",
      "Offline viewing",
      "1-on-1 mentorship sessions",
    ],
    cta: "Start Free Trial",
    highlighted: true,
  },
  {
    id: 3,
    name: "Enterprise",
    price: 99,
    period: "month",
    description: "For teams and organizations",
    features: [
      "Everything in Pro",
      "Team management dashboard",
      "Custom learning paths",
      "Advanced analytics",
      "Dedicated account manager",
      "Custom integrations",
      "SLA guarantee",
    ],
    cta: "Contact Sales",
    highlighted: false,
  },
];

export const categories = [
  "All",
  "Web Development",
  "Data Science",
  "Design",
  "Marketing",
  "Mobile Development",
  "Cloud Computing",
  "Business",
  "Photography",
];