import { db } from '@/db';
import { lessons } from '@/db/schema';

async function main() {
    const sampleLessons = [
        // Complete Web Development Bootcamp - Section 1: HTML Fundamentals
        {
            courseId: 1,
            sectionTitle: 'HTML Fundamentals',
            title: 'Introduction to HTML',
            duration: '12:45',
            videoUrl: 'https://example.com/videos/html-intro.mp4',
            transcript: 'Welcome to HTML fundamentals. HTML stands for HyperText Markup Language and is the foundation of all web pages. In this lesson, we will explore what HTML is, how it works, and why it is essential for web development.',
            orderIndex: 1,
            locked: false,
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'HTML Fundamentals',
            title: 'HTML Elements and Tags',
            duration: '18:30',
            videoUrl: 'https://example.com/videos/html-elements.mp4',
            transcript: 'HTML elements are the building blocks of web pages. Each element is defined by tags that tell the browser how to structure and display content. We will cover common elements like headings, paragraphs, links, and images.',
            orderIndex: 2,
            locked: false,
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'HTML Fundamentals',
            title: 'Creating HTML Forms',
            duration: '22:15',
            videoUrl: 'https://example.com/videos/html-forms.mp4',
            transcript: 'Forms are essential for user interaction on websites. Learn how to create input fields, buttons, dropdowns, and other form elements. We will also cover form validation and best practices for user experience.',
            orderIndex: 3,
            locked: true,
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'HTML Fundamentals',
            title: 'Semantic HTML and Accessibility',
            duration: '16:20',
            videoUrl: 'https://example.com/videos/semantic-html.mp4',
            transcript: 'Semantic HTML uses meaningful elements to describe content structure. This improves accessibility for screen readers and helps search engines understand your content better. Learn about header, nav, main, section, article, and footer elements.',
            orderIndex: 4,
            locked: true,
            createdAt: new Date('2024-01-13').toISOString(),
        },

        // Complete Web Development Bootcamp - Section 2: CSS Styling
        {
            courseId: 1,
            sectionTitle: 'CSS Styling',
            title: 'CSS Basics and Selectors',
            duration: '15:45',
            videoUrl: 'https://example.com/videos/css-basics.mp4',
            transcript: 'CSS (Cascading Style Sheets) controls the visual presentation of HTML elements. Learn about selectors, properties, values, and the cascade. We will cover element, class, and ID selectors along with specificity rules.',
            orderIndex: 5,
            locked: false,
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'CSS Styling',
            title: 'Flexbox Layout System',
            duration: '25:10',
            videoUrl: 'https://example.com/videos/flexbox.mp4',
            transcript: 'Flexbox is a powerful layout method for arranging elements in one dimension. Master flex containers, flex items, and properties like justify-content, align-items, and flex-wrap to create responsive layouts.',
            orderIndex: 6,
            locked: true,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'CSS Styling',
            title: 'CSS Grid Layout',
            duration: '23:35',
            videoUrl: 'https://example.com/videos/css-grid.mp4',
            transcript: 'CSS Grid provides two-dimensional layout control. Learn to create complex layouts with grid-template-columns, grid-template-rows, and grid areas. Perfect for creating responsive designs with precise control.',
            orderIndex: 7,
            locked: true,
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'CSS Styling',
            title: 'Responsive Design Principles',
            duration: '20:25',
            videoUrl: 'https://example.com/videos/responsive-design.mp4',
            transcript: 'Create websites that work on all devices using responsive design principles. Learn about media queries, fluid grids, flexible images, and mobile-first design approach for optimal user experience.',
            orderIndex: 8,
            locked: true,
            createdAt: new Date('2024-01-17').toISOString(),
        },

        // Complete Web Development Bootcamp - Section 3: JavaScript Essentials
        {
            courseId: 1,
            sectionTitle: 'JavaScript Essentials',
            title: 'JavaScript Fundamentals',
            duration: '19:50',
            videoUrl: 'https://example.com/videos/js-fundamentals.mp4',
            transcript: 'JavaScript brings interactivity to web pages. Learn about variables, data types, operators, and control structures. Understand the basics of functions, scope, and how JavaScript executes in the browser.',
            orderIndex: 9,
            locked: false,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'JavaScript Essentials',
            title: 'DOM Manipulation',
            duration: '24:15',
            videoUrl: 'https://example.com/videos/dom-manipulation.mp4',
            transcript: 'The Document Object Model (DOM) represents the structure of HTML documents. Learn to select elements, modify content, change styles, and create dynamic web pages using JavaScript DOM methods.',
            orderIndex: 10,
            locked: true,
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'JavaScript Essentials',
            title: 'Event Handling',
            duration: '17:40',
            videoUrl: 'https://example.com/videos/event-handling.mp4',
            transcript: 'Events make web pages interactive. Learn about click events, form submissions, keyboard inputs, and mouse interactions. Understand event listeners, event objects, and event delegation patterns.',
            orderIndex: 11,
            locked: true,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'JavaScript Essentials',
            title: 'Async/Await and Promises',
            duration: '21:30',
            videoUrl: 'https://example.com/videos/async-await.mp4',
            transcript: 'Handle asynchronous operations with promises and async/await syntax. Learn to make API calls, handle loading states, and manage errors in asynchronous JavaScript code for better user experience.',
            orderIndex: 12,
            locked: true,
            createdAt: new Date('2024-01-21').toISOString(),
        },

        // Complete Web Development Bootcamp - Section 4: React Development
        {
            courseId: 1,
            sectionTitle: 'React Development',
            title: 'React Basics and JSX',
            duration: '18:25',
            videoUrl: 'https://example.com/videos/react-basics.mp4',
            transcript: 'React is a JavaScript library for building user interfaces. Learn about components, JSX syntax, and the virtual DOM. Understand how React makes building interactive UIs more efficient and maintainable.',
            orderIndex: 13,
            locked: true,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'React Development',
            title: 'Components and Props',
            duration: '22:05',
            videoUrl: 'https://example.com/videos/react-components.mp4',
            transcript: 'Components are the building blocks of React applications. Learn to create functional and class components, pass data through props, and compose complex UIs from simple, reusable components.',
            orderIndex: 14,
            locked: true,
            createdAt: new Date('2024-01-23').toISOString(),
        },
        {
            courseId: 1,
            sectionTitle: 'React Development',
            title: 'State Management with Hooks',
            duration: '25:45',
            videoUrl: 'https://example.com/videos/react-state.mp4',
            transcript: 'State management is crucial for dynamic React applications. Master useState, useEffect, and other React hooks to manage component state, side effects, and create interactive user interfaces.',
            orderIndex: 15,
            locked: true,
            createdAt: new Date('2024-01-24').toISOString(),
        },

        // Python Data Science Complete Course - Section 1: Python Basics
        {
            courseId: 3,
            sectionTitle: 'Python Basics',
            title: 'Python Syntax and Variables',
            duration: '14:30',
            videoUrl: 'https://example.com/videos/python-syntax.mp4',
            transcript: 'Learn Python syntax fundamentals including variables, naming conventions, and basic operations. Python is known for its readable syntax and powerful capabilities in data science and web development.',
            orderIndex: 1,
            locked: false,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            courseId: 3,
            sectionTitle: 'Python Basics',
            title: 'Data Types and Structures',
            duration: '19:15',
            videoUrl: 'https://example.com/videos/python-data-types.mp4',
            transcript: 'Explore Python data types including strings, integers, floats, booleans, lists, dictionaries, and tuples. Understanding data structures is essential for effective data manipulation and analysis.',
            orderIndex: 2,
            locked: false,
            createdAt: new Date('2024-01-26').toISOString(),
        },
        {
            courseId: 3,
            sectionTitle: 'Python Basics',
            title: 'Control Flow and Functions',
            duration: '16:45',
            videoUrl: 'https://example.com/videos/python-control-flow.mp4',
            transcript: 'Master control flow statements like if/else, loops, and exception handling. Learn to write functions, understand scope, and create modular, reusable code for data science applications.',
            orderIndex: 3,
            locked: true,
            createdAt: new Date('2024-01-27').toISOString(),
        },

        // Python Data Science Complete Course - Section 2: Data Manipulation
        {
            courseId: 3,
            sectionTitle: 'Data Manipulation',
            title: 'Pandas Basics and DataFrames',
            duration: '23:20',
            videoUrl: 'https://example.com/videos/pandas-basics.mp4',
            transcript: 'Pandas is the cornerstone of data analysis in Python. Learn to create, read, and manipulate DataFrames. Understand Series, indexing, and basic operations that form the foundation of data science.',
            orderIndex: 4,
            locked: false,
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            courseId: 3,
            sectionTitle: 'Data Manipulation',
            title: 'Data Cleaning Techniques',
            duration: '21:10',
            videoUrl: 'https://example.com/videos/data-cleaning.mp4',
            transcript: 'Real-world data is messy. Learn essential data cleaning techniques including handling missing values, removing duplicates, data type conversions, and dealing with outliers to prepare data for analysis.',
            orderIndex: 5,
            locked: true,
            createdAt: new Date('2024-01-29').toISOString(),
        },
        {
            courseId: 3,
            sectionTitle: 'Data Manipulation',
            title: 'Exploratory Data Analysis',
            duration: '18:35',
            videoUrl: 'https://example.com/videos/data-analysis.mp4',
            transcript: 'Discover insights in your data through exploratory data analysis. Learn statistical summaries, grouping operations, filtering, and aggregation techniques to understand data patterns and relationships.',
            orderIndex: 6,
            locked: true,
            createdAt: new Date('2024-01-30').toISOString(),
        },
        {
            courseId: 3,
            sectionTitle: 'Data Manipulation',
            title: 'Data Visualization with Matplotlib',
            duration: '20:50',
            videoUrl: 'https://example.com/videos/data-visualization.mp4',
            transcript: 'Visualize data effectively using Matplotlib and Seaborn. Create plots, charts, and graphs to communicate insights. Learn about different plot types, customization, and best practices for data visualization.',
            orderIndex: 7,
            locked: true,
            createdAt: new Date('2024-01-31').toISOString(),
        },

        // Python Data Science Complete Course - Section 3: Machine Learning
        {
            courseId: 3,
            sectionTitle: 'Machine Learning',
            title: 'Introduction to Scikit-learn',
            duration: '17:25',
            videoUrl: 'https://example.com/videos/scikit-learn-intro.mp4',
            transcript: 'Scikit-learn is the most popular machine learning library in Python. Learn about the library structure, common workflows, and how to prepare data for machine learning algorithms.',
            orderIndex: 8,
            locked: true,
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            courseId: 3,
            sectionTitle: 'Machine Learning',
            title: 'Model Training and Algorithms',
            duration: '24:40',
            videoUrl: 'https://example.com/videos/model-training.mp4',
            transcript: 'Explore supervised learning algorithms including linear regression, decision trees, and random forests. Learn the training process, feature selection, and how to choose the right algorithm for your problem.',
            orderIndex: 9,
            locked: true,
            createdAt: new Date('2024-02-02').toISOString(),
        },
        {
            courseId: 3,
            sectionTitle: 'Machine Learning',
            title: 'Model Evaluation and Validation',
            duration: '19:55',
            videoUrl: 'https://example.com/videos/model-evaluation.mp4',
            transcript: 'Learn to evaluate model performance using metrics like accuracy, precision, recall, and F1-score. Understand cross-validation, train-test splits, and techniques to avoid overfitting in machine learning models.',
            orderIndex: 10,
            locked: true,
            createdAt: new Date('2024-02-03').toISOString(),
        },
    ];

    await db.insert(lessons).values(sampleLessons);
    
    console.log('✅ Lessons seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});